name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install PyInstaller
      run: pip install pyinstaller
        
    - name: Install NSIS
      shell: pwsh
      run: |
        choco install nsis -y
        
    - name: Prepare Files
      shell: pwsh
      run: |
        # Create dist directory structure
        New-Item -Path "dist\calculator" -ItemType Directory -Force
        New-Item -Path "dist\calculator\lib" -ItemType Directory -Force
        New-Item -Path "dist\calculator\lib\fonts" -ItemType Directory -Force
        New-Item -Path "dist\gridset" -ItemType Directory -Force
        
        # Copy calculator files and libraries
        Copy-Item "vanilla-html\calcstandalone.html" -Destination "dist\calculator\"
        Copy-Item "vanilla-html\lib\*" -Destination "dist\calculator\lib\"
        Copy-Item "vanilla-html\lib\fonts\*" -Destination "dist\calculator\lib\fonts\"
        Copy-Item "resources\logo_44I_icon.ico" -Destination "dist\"
        Copy-Item "resources\ScientificCalc.gridset" -Destination "dist\gridset\"
        
        # Build CreateGridSet executable
        pyinstaller vanilla-html\CreateGridSet.py --noupx --noconsole --onedir --clean -y
        
        # Copy CreateGridSet files to dist
        Copy-Item "dist\CreateGridSet\*" -Destination "dist\gridset\" -Recurse
        
    - name: Build Installer
      shell: pwsh
      run: |
        # Run NSIS
        Push-Location scripts
        & 'C:\Program Files (x86)\NSIS\makensis.exe' windows-installer.nsi
        Pop-Location
        
        # Move installer from scripts to root directory
        Move-Item -Path "scripts\ScientificCalculator-Setup.exe" -Destination "ScientificCalculator-Setup.exe"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nsis-installer
        path: ScientificCalculator-Setup.exe
        
    - name: Upload to release
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      with:
        files: ScientificCalculator-Setup.exe