name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    env:
      UV_PATH: C:\Users\runneradmin\.local\bin
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install and setup uv
      shell: pwsh
      run: |
        iwr https://astral.sh/uv/install.ps1 -useb | iex
        echo "$env:UV_PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Install dependencies
      shell: pwsh
      run: |
        uv pip install .[build]
        
    - name: Install NSIS
      run: |
        choco install nsis -y
        
    - name: Build executable
      shell: pwsh
      run: |
        uv pip install pyinstaller
        uv run pyinstaller --name scicalc --onefile --noconsole --icon=resources/logo_44I_icon.ico --add-data "src/scicalc;scicalc" src/scicalc/cli.py
        
    - name: Build Installer
      run: |
        & 'C:\Program Files (x86)\NSIS\makensis.exe' scripts/windows-installer.nsi
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: ScientificCalculator-Setup.exe
        
    - name: Upload to release
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      with:
        files: ScientificCalculator-Setup.exe